documents:
- source_id: tax-forms-2022-n11ins-236e06ce82
  jurisdiction: us-hi
  document_class: form
  citation_path: us-hi/form/individual_income_tax_forms/files.hawaii.gov/tax/forms/2022/n11ins
  title: n11ins
  source_url: https://files.hawaii.gov/tax/forms/2022/n11ins.pdf
  source_format: pdf
  source_as_of: '2026-05-24'
  metadata:
    primary_source: true
    source_authority: files.hawaii.gov
    source_discovery_group: us-hi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 11
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://files.hawaii.gov/tax/forms/2022/n11ins.pdf
    discovered_via: source-discovery:all_url
- source_id: tax-forms-2021-n11ins-7297450ccd
  jurisdiction: us-hi
  document_class: form
  citation_path: us-hi/form/individual_income_tax_forms/files.hawaii.gov/tax/forms/2021/n11ins
  title: n11ins
  source_url: https://files.hawaii.gov/tax/forms/2021/n11ins.pdf
  source_format: pdf
  source_as_of: '2026-05-24'
  metadata:
    primary_source: true
    source_authority: files.hawaii.gov
    source_discovery_group: us-hi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 5
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://files.hawaii.gov/tax/forms/2021/n11ins.pdf#page=13
    discovered_via: source-discovery:all_url
- source_id: tax-forms-2024-n11ins-f94b1f29b0
  jurisdiction: us-hi
  document_class: form
  citation_path: us-hi/form/individual_income_tax_forms/files.hawaii.gov/tax/forms/2024/n11ins
  title: n11ins
  source_url: https://files.hawaii.gov/tax/forms/2024/n11ins.pdf
  source_format: pdf
  source_as_of: '2026-05-24'
  metadata:
    primary_source: true
    source_authority: files.hawaii.gov
    source_discovery_group: us-hi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 4
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://files.hawaii.gov/tax/forms/2024/n11ins.pdf#page=13
    discovered_via: source-discovery:all_url
- source_id: tax-forms-2023-n11ins-9a2873a1f5
  jurisdiction: us-hi
  document_class: form
  citation_path: us-hi/form/individual_income_tax_forms/files.hawaii.gov/tax/forms/2023/n11ins
  title: n11ins
  source_url: https://files.hawaii.gov/tax/forms/2023/n11ins.pdf
  source_format: pdf
  source_as_of: '2026-05-24'
  metadata:
    primary_source: true
    source_authority: files.hawaii.gov
    source_discovery_group: us-hi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 3
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://files.hawaii.gov/tax/forms/2023/n11ins.pdf#page=13
    discovered_via: source-discovery:all_url
- source_id: tax-forms-2018-n11ins-fc1847a19b
  jurisdiction: us-hi
  document_class: form
  citation_path: us-hi/form/individual_income_tax_forms/files.hawaii.gov/tax/forms/2018/n11ins
  title: n11ins
  source_url: https://files.hawaii.gov/tax/forms/2018/n11ins.pdf
  source_format: pdf
  source_as_of: '2026-05-24'
  metadata:
    primary_source: true
    source_authority: files.hawaii.gov
    source_discovery_group: us-hi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 2
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://files.hawaii.gov/tax/forms/2018/n11ins.pdf#page=19
    discovered_via: source-discovery:all_url
- source_id: tax-forms-2019-n11ins-475a86f8ee
  jurisdiction: us-hi
  document_class: form
  citation_path: us-hi/form/individual_income_tax_forms/files.hawaii.gov/tax/forms/2019/n11ins
  title: n11ins
  source_url: https://files.hawaii.gov/tax/forms/2019/n11ins.pdf
  source_format: pdf
  source_as_of: '2026-05-24'
  metadata:
    primary_source: true
    source_authority: files.hawaii.gov
    source_discovery_group: us-hi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 2
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://files.hawaii.gov/tax/forms/2019/n11ins.pdf#page=19
    discovered_via: source-discovery:all_url
- source_id: tax-forms-2020-n11ins-b37c6191ac
  jurisdiction: us-hi
  document_class: form
  citation_path: us-hi/form/individual_income_tax_forms/files.hawaii.gov/tax/forms/2020/n11ins
  title: n11ins
  source_url: https://files.hawaii.gov/tax/forms/2020/n11ins.pdf
  source_format: pdf
  source_as_of: '2026-05-24'
  metadata:
    primary_source: true
    source_authority: files.hawaii.gov
    source_discovery_group: us-hi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 2
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://files.hawaii.gov/tax/forms/2020/n11ins.pdf#page=19
    discovered_via: source-discovery:all_url
- source_id: tax-forms-2021-n11_i-a2167025f5
  jurisdiction: us-hi
  document_class: form
  citation_path: us-hi/form/individual_income_tax_forms/files.hawaii.gov/tax/forms/2021/n11_i
  title: n11_i
  source_url: https://files.hawaii.gov/tax/forms/2021/n11_i.pdf
  source_format: pdf
  source_as_of: '2026-05-24'
  metadata:
    primary_source: true
    source_authority: files.hawaii.gov
    source_discovery_group: us-hi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 2
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://files.hawaii.gov/tax/forms/2021/n11_i.pdf#page=2
    discovered_via: source-discovery:all_url
- source_id: tax-forms-2022-n11_i-2910496706
  jurisdiction: us-hi
  document_class: form
  citation_path: us-hi/form/individual_income_tax_forms/files.hawaii.gov/tax/forms/2022/n11_i
  title: n11_i
  source_url: https://files.hawaii.gov/tax/forms/2022/n11_i.pdf
  source_format: pdf
  source_as_of: '2026-05-24'
  metadata:
    primary_source: true
    source_authority: files.hawaii.gov
    source_discovery_group: us-hi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 2
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://files.hawaii.gov/tax/forms/2022/n11_i.pdf#page=2
    discovered_via: source-discovery:all_url
- source_id: tax-forms-2024-n11_i-4fb16812bd
  jurisdiction: us-hi
  document_class: form
  citation_path: us-hi/form/individual_income_tax_forms/files.hawaii.gov/tax/forms/2024/n11_i
  title: n11_i
  source_url: https://files.hawaii.gov/tax/forms/2024/n11_i.pdf
  source_format: pdf
  source_as_of: '2026-05-24'
  metadata:
    primary_source: true
    source_authority: files.hawaii.gov
    source_discovery_group: us-hi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 1
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://files.hawaii.gov/tax/forms/2024/n11_i.pdf#page=3
    discovered_via: source-discovery:all_url
