documents:
- source_id: taxes---media-project-websites-taxes-forms-iit-ty2023-book_mi-1040-90769ee2ce
  jurisdiction: us-mi
  document_class: form
  citation_path: us-mi/form/individual_income_tax_forms/michigan.gov/taxes/source/media/project/websites/taxes/forms/iit/ty2023/book_mi-1040
  title: BOOK_MI-1040
  source_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/IIT/TY2023/BOOK_MI-1040.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: michigan.gov
    source_discovery_group: us-mi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 15
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/2023/2023-IIT-Forms/BOOK_MI-1040.pdf#page=10
    source_discovery_canonical_url: https://michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/2023/2023-IIT-Forms/BOOK_MI-1040.pdf
    source_url_rewritten: true
    discovered_via: source-discovery:all_url
- source_id: taxes---media-project-websites-taxes-forms-iit-ty2022-book_mi-1040-b882f24bb3
  jurisdiction: us-mi
  document_class: form
  citation_path: us-mi/form/individual_income_tax_forms/michigan.gov/taxes/source/media/project/websites/taxes/forms/iit/ty2022/book_mi-1040
  title: BOOK_MI-1040
  source_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/IIT/TY2022/BOOK_MI-1040.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: michigan.gov
    source_discovery_group: us-mi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 14
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/2022/2022-IIT-Forms/BOOK_MI-1040.pdf
    source_discovery_canonical_url: https://michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/2022/2022-IIT-Forms/BOOK_MI-1040.pdf
    source_url_rewritten: true
    discovered_via: source-discovery:all_url
- source_id: taxes---media-project-websites-taxes-forms-iit-ty2024-mi-1040-instructio-fe1701beb3
  jurisdiction: us-mi
  document_class: form
  citation_path: us-mi/form/individual_income_tax_forms/michigan.gov/taxes/source/media/project/websites/taxes/forms/iit/ty2024/mi-1040-instructions
  title: MI-1040-Instructions
  source_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/IIT/TY2024/MI-1040-Instructions.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: michigan.gov
    source_discovery_group: us-mi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 12
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/IIT/TY2024/MI-1040-Instructions.pdf#page=10
    source_discovery_canonical_url: https://michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/IIT/TY2024/MI-1040-Instructions.pdf
    source_url_rewritten: true
    discovered_via: source-discovery:all_url
- source_id: taxes---media-project-websites-taxes-forms-iit-ty2025-mi-1040-book-df8231a4af
  jurisdiction: us-mi
  document_class: form
  citation_path: us-mi/form/individual_income_tax_forms/michigan.gov/taxes/source/media/project/websites/taxes/forms/iit/ty2025/mi-1040-book
  title: MI-1040-Book
  source_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/IIT/TY2025/MI-1040-Book.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: michigan.gov
    source_discovery_group: us-mi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 7
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/IIT/TY2025/MI-1040-Book.pdf#page=10
    source_discovery_canonical_url: https://michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/IIT/TY2025/MI-1040-Book.pdf
    source_url_rewritten: true
    discovered_via: source-discovery:all_url
- source_id: taxes---media-project-websites-taxes-forms-iit-ty2022-mi-1040-84aa3604ed
  jurisdiction: us-mi
  document_class: form
  citation_path: us-mi/form/individual_income_tax_forms/michigan.gov/taxes/source/media/project/websites/taxes/forms/iit/ty2022/mi-1040
  title: MI-1040
  source_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/IIT/TY2022/MI-1040.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: michigan.gov
    source_discovery_group: us-mi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 2
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/2022/2022-IIT-Forms/MI-1040.pdf
    source_discovery_canonical_url: https://michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/2022/2022-IIT-Forms/MI-1040.pdf
    source_url_rewritten: true
    discovered_via: source-discovery:all_url
- source_id: taxes---media-project-websites-taxes-forms-iit-ty2022-mi-1040cr-4a7d370d1f
  jurisdiction: us-mi
  document_class: form
  citation_path: us-mi/form/individual_income_tax_forms/michigan.gov/taxes/source/media/project/websites/taxes/forms/iit/ty2022/mi-1040cr
  title: MI-1040CR
  source_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/IIT/TY2022/MI-1040CR.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: michigan.gov
    source_discovery_group: us-mi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 2
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/2022/2022-IIT-Forms/MI-1040CR.pdf#page=1
    source_discovery_canonical_url: https://michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/2022/2022-IIT-Forms/MI-1040CR.pdf
    source_url_rewritten: true
    discovered_via: source-discovery:all_url
- source_id: taxes---media-project-websites-taxes-forms-iit-ty2023-mi-1040cr-48cdc8aa03
  jurisdiction: us-mi
  document_class: form
  citation_path: us-mi/form/individual_income_tax_forms/michigan.gov/taxes/source/media/project/websites/taxes/forms/iit/ty2023/mi-1040cr
  title: MI-1040CR
  source_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/IIT/TY2023/MI-1040CR.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: michigan.gov
    source_discovery_group: us-mi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 2
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/2023/2023-IIT-Forms/MI-1040CR.pdf#page=1
    source_discovery_canonical_url: https://michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/2023/2023-IIT-Forms/MI-1040CR.pdf
    source_url_rewritten: true
    discovered_via: source-discovery:all_url
- source_id: taxes---media-project-websites-taxes-forms-iit-ty2024-mi-1040cr-fdffa6f665
  jurisdiction: us-mi
  document_class: form
  citation_path: us-mi/form/individual_income_tax_forms/michigan.gov/taxes/source/media/project/websites/taxes/forms/iit/ty2024/mi-1040cr
  title: MI-1040CR
  source_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/IIT/TY2024/MI-1040CR.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: michigan.gov
    source_discovery_group: us-mi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 2
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/IIT/TY2024/MI-1040CR.pdf#page=1
    source_discovery_canonical_url: https://michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/IIT/TY2024/MI-1040CR.pdf
    source_url_rewritten: true
    discovered_via: source-discovery:all_url
- source_id: taxes---media-project-websites-taxes-forms-iit-ty2025-mi-1040cr-9ea1334921
  jurisdiction: us-mi
  document_class: form
  citation_path: us-mi/form/individual_income_tax_forms/michigan.gov/taxes/source/media/project/websites/taxes/forms/iit/ty2025/mi-1040cr
  title: MI-1040CR
  source_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/IIT/TY2025/MI-1040CR.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: michigan.gov
    source_discovery_group: us-mi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 2
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/IIT/TY2025/MI-1040CR.pdf#page=1
    source_discovery_canonical_url: https://michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/IIT/TY2025/MI-1040CR.pdf
    source_url_rewritten: true
    discovered_via: source-discovery:all_url
- source_id: taxes---media-project-websites-taxes-forms-iit-ty2020-book_mi-1040_instr-e89f1d461d
  jurisdiction: us-mi
  document_class: form
  citation_path: us-mi/form/individual_income_tax_forms/michigan.gov/taxes/source/media/project/websites/taxes/forms/iit/ty2020/book_mi-1040_instructions_only
  title: Book_MI-1040_instructions_only
  source_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/IIT/TY2020/Book_MI-1040_instructions_only.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: michigan.gov
    source_discovery_group: us-mi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 1
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://www.michigan.gov/-/media/Project/Websites/taxes/Forms/2020/2020-IIT-Forms/Book_MI-1040_instructions_only.pdf#page=15
    source_discovery_canonical_url: https://michigan.gov/-/media/Project/Websites/taxes/Forms/2020/2020-IIT-Forms/Book_MI-1040_instructions_only.pdf
    source_url_rewritten: true
    discovered_via: source-discovery:all_url
- source_id: taxes---media-project-websites-taxes-forms-iit-ty2023-mi-1040-0a334df57d
  jurisdiction: us-mi
  document_class: form
  citation_path: us-mi/form/individual_income_tax_forms/michigan.gov/taxes/source/media/project/websites/taxes/forms/iit/ty2023/mi-1040
  title: MI-1040
  source_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/IIT/TY2023/MI-1040.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: michigan.gov
    source_discovery_group: us-mi/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 1
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/2023/2023-IIT-Forms/MI-1040.pdf#page=2
    source_discovery_canonical_url: https://michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/2023/2023-IIT-Forms/MI-1040.pdf
    source_url_rewritten: true
    discovered_via: source-discovery:all_url
