documents:
- source_id: content-dam-mdcomp-tax-instructions-2023-resident-booklet-a7370e940d
  jurisdiction: us-md
  document_class: form
  citation_path: us-md/form/tax_forms/marylandtaxes.gov/content/dam/mdcomp/tax/instructions/2023/resident-booklet
  title: Resident-Booklet
  source_url: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2023/Resident-Booklet.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: marylandtaxes.gov
    source_discovery_group: us-md/form/tax_forms
    source_family: tax_forms
    source_status: primary_official
    source_discovery_input_count: 11
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://www.marylandtaxes.gov/forms/23_forms/Resident-Booklet.pdf#page=11
    source_discovery_canonical_url: https://marylandtaxes.gov/forms/23_forms/Resident-Booklet.pdf
    source_url_rewritten: true
    discovered_via: source-discovery:all_url
- source_id: content-dam-mdcomp-tax-instructions-2024-resident-booklet-7cb7b6ae36
  jurisdiction: us-md
  document_class: form
  citation_path: us-md/form/tax_forms/marylandtaxes.gov/content/dam/mdcomp/tax/instructions/2024/resident-booklet
  title: Resident-Booklet
  source_url: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2024/Resident-Booklet.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: marylandtaxes.gov
    source_discovery_group: us-md/form/tax_forms
    source_family: tax_forms
    source_status: primary_official
    source_discovery_input_count: 9
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://www.marylandtaxes.gov/forms/24-forms/Resident-Booklet.pdf#page=12
    source_discovery_canonical_url: https://marylandtaxes.gov/forms/24-forms/Resident-Booklet.pdf
    source_url_rewritten: true
    discovered_via: source-discovery:all_url
- source_id: content-dam-mdcomp-tax-forms-2023-502cr-c6ae2a5281
  jurisdiction: us-md
  document_class: form
  citation_path: us-md/form/tax_forms/marylandtaxes.gov/content/dam/mdcomp/tax/forms/2023/502cr
  title: 502CR
  source_url: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/forms/2023/502CR.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: marylandtaxes.gov
    source_discovery_group: us-md/form/tax_forms
    source_family: tax_forms
    source_status: primary_official
    source_discovery_input_count: 2
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://marylandtaxes.gov/forms/23_forms/502CR.pdf#page=6
    source_discovery_canonical_url: https://marylandtaxes.gov/forms/23_forms/502CR.pdf
    source_url_rewritten: true
    discovered_via: source-discovery:all_url
- source_id: content-dam-mdcomp-tax-forms-2024-502cr-b979330357
  jurisdiction: us-md
  document_class: form
  citation_path: us-md/form/tax_forms/marylandtaxes.gov/content/dam/mdcomp/tax/forms/2024/502cr
  title: 502CR
  source_url: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/forms/2024/502CR.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: marylandtaxes.gov
    source_discovery_group: us-md/form/tax_forms
    source_family: tax_forms
    source_status: primary_official
    source_discovery_input_count: 1
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://marylandtaxes.gov/forms/24-forms/502CR.pdf#page=7
    source_discovery_canonical_url: https://marylandtaxes.gov/forms/24-forms/502CR.pdf
    source_url_rewritten: true
    discovered_via: source-discovery:all_url
- source_id: content-dam-mdcomp-tax-instructions-2024-nonresident-booklet-b4cb2a71d9
  jurisdiction: us-md
  document_class: form
  citation_path: us-md/form/tax_forms/marylandtaxes.gov/content/dam/mdcomp/tax/instructions/2024/nonresident-booklet
  title: Nonresident-Booklet
  source_url: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2024/Nonresident-Booklet.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: marylandtaxes.gov
    source_discovery_group: us-md/form/tax_forms
    source_family: tax_forms
    source_status: primary_official
    source_discovery_input_count: 1
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://www.marylandtaxes.gov/forms/24-forms/Nonresident-Booklet.pdf#page=13
    source_discovery_canonical_url: https://marylandtaxes.gov/forms/24-forms/Nonresident-Booklet.pdf
    source_url_rewritten: true
    discovered_via: source-discovery:all_url
