documents:
- source_id: sites-dor-files-forms-sc1040instr_2025-a3b26ff542
  jurisdiction: us-sc
  document_class: form
  citation_path: us-sc/form/individual_income_tax_forms/dor.sc.gov/sites/dor/files/forms/sc1040instr_2025
  title: SC1040Instr_2025
  source_url: https://dor.sc.gov/sites/dor/files/forms/SC1040Instr_2025.pdf
  source_format: pdf
  source_as_of: '2026-05-24'
  metadata:
    primary_source: true
    source_authority: dor.sc.gov
    source_discovery_group: us-sc/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 10
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://dor.sc.gov/sites/dor/files/forms/SC1040Instr_2025.pdf#page=1
    discovered_via: source-discovery:all_url
- source_id: forms-site-forms-sc1040instr_2024-763b47e235
  jurisdiction: us-sc
  document_class: form
  citation_path: us-sc/form/individual_income_tax_forms/dor.sc.gov/forms-site/forms/sc1040instr_2024
  title: SC1040Instr_2024
  source_url: https://dor.sc.gov/forms-site/Forms/SC1040Instr_2024.pdf
  source_format: pdf
  source_as_of: '2026-05-24'
  metadata:
    primary_source: true
    source_authority: dor.sc.gov
    source_discovery_group: us-sc/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 9
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://dor.sc.gov/forms-site/Forms/SC1040Instr_2024.pdf#page=10
    discovered_via: source-discovery:all_url
- source_id: forms-site-forms-sc1040_2021-8be86165e4
  jurisdiction: us-sc
  document_class: form
  citation_path: us-sc/form/individual_income_tax_forms/dor.sc.gov/forms-site/forms/sc1040_2021
  title: SC1040_2021
  source_url: https://dor.sc.gov/forms-site/Forms/SC1040_2021.pdf
  source_format: pdf
  source_as_of: '2026-05-24'
  metadata:
    primary_source: true
    source_authority: dor.sc.gov
    source_discovery_group: us-sc/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 3
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://dor.sc.gov/forms-site/Forms/SC1040_2021.pdf
    discovered_via: source-discovery:all_url
- source_id: forms-site-forms-sc1040_2022-98155d802d
  jurisdiction: us-sc
  document_class: form
  citation_path: us-sc/form/individual_income_tax_forms/dor.sc.gov/forms-site/forms/sc1040_2022
  title: SC1040_2022
  source_url: https://dor.sc.gov/forms-site/Forms/SC1040_2022.pdf
  source_format: pdf
  source_as_of: '2026-05-24'
  metadata:
    primary_source: true
    source_authority: dor.sc.gov
    source_discovery_group: us-sc/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 3
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://dor.sc.gov/forms-site/Forms/SC1040_2022.pdf
    discovered_via: source-discovery:all_url
- source_id: forms-site-forms-sc1040tt_2021-f4bf5825ee
  jurisdiction: us-sc
  document_class: form
  citation_path: us-sc/form/individual_income_tax_forms/dor.sc.gov/forms-site/forms/sc1040tt_2021
  title: SC1040TT_2021
  source_url: https://dor.sc.gov/forms-site/Forms/SC1040TT_2021.pdf
  source_format: pdf
  source_as_of: '2026-05-24'
  metadata:
    primary_source: true
    source_authority: dor.sc.gov
    source_discovery_group: us-sc/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 1
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://dor.sc.gov/forms-site/Forms/SC1040TT_2021.pdf
    discovered_via: source-discovery:all_url
- source_id: forms-site-forms-sc1040tt_2022-7ba2f7238e
  jurisdiction: us-sc
  document_class: form
  citation_path: us-sc/form/individual_income_tax_forms/dor.sc.gov/forms-site/forms/sc1040tt_2022
  title: SC1040TT_2022
  source_url: https://dor.sc.gov/forms-site/Forms/SC1040TT_2022.pdf
  source_format: pdf
  source_as_of: '2026-05-24'
  metadata:
    primary_source: true
    source_authority: dor.sc.gov
    source_discovery_group: us-sc/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 1
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://dor.sc.gov/forms-site/Forms/SC1040TT_2022.pdf
    discovered_via: source-discovery:all_url
- source_id: forms-site-forms-sc1040tt_2024-e9c38d10ec
  jurisdiction: us-sc
  document_class: form
  citation_path: us-sc/form/individual_income_tax_forms/dor.sc.gov/forms-site/forms/sc1040tt_2024
  title: SC1040TT_2024
  source_url: https://dor.sc.gov/forms-site/Forms/SC1040TT_2024.pdf
  source_format: pdf
  source_as_of: '2026-05-24'
  metadata:
    primary_source: true
    source_authority: dor.sc.gov
    source_discovery_group: us-sc/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 1
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://dor.sc.gov/forms-site/Forms/SC1040TT_2024.pdf#page=1
    discovered_via: source-discovery:all_url
- source_id: forms-site-forms-sc1040_2020-32c4e02825
  jurisdiction: us-sc
  document_class: form
  citation_path: us-sc/form/individual_income_tax_forms/dor.sc.gov/forms-site/forms/sc1040_2020
  title: SC1040_2020
  source_url: https://dor.sc.gov/forms-site/Forms/SC1040_2020.pdf
  source_format: pdf
  source_as_of: '2026-05-24'
  metadata:
    primary_source: true
    source_authority: dor.sc.gov
    source_discovery_group: us-sc/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 1
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://dor.sc.gov/forms-site/Forms/SC1040_2020.pdf
    discovered_via: source-discovery:all_url
- source_id: forms-site-forms-sc1040inst_2022-6b4e3e0875
  jurisdiction: us-sc
  document_class: form
  citation_path: us-sc/form/individual_income_tax_forms/dor.sc.gov/forms-site/forms/sc1040inst_2022
  title: SC1040inst_2022
  source_url: https://dor.sc.gov/forms-site/Forms/SC1040inst_2022.pdf
  source_format: pdf
  source_as_of: '2026-05-24'
  metadata:
    primary_source: true
    source_authority: dor.sc.gov
    source_discovery_group: us-sc/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 1
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://dor.sc.gov/forms-site/Forms/SC1040inst_2022.pdf#page=2
    discovered_via: source-discovery:all_url
- source_id: sites-dor-files-forms-sc1040_2025-cbb594f984
  jurisdiction: us-sc
  document_class: form
  citation_path: us-sc/form/individual_income_tax_forms/dor.sc.gov/sites/dor/files/forms/sc1040_2025
  title: SC1040_2025
  source_url: https://dor.sc.gov/sites/dor/files/forms/SC1040_2025.pdf
  source_format: pdf
  source_as_of: '2026-05-24'
  metadata:
    primary_source: true
    source_authority: dor.sc.gov
    source_discovery_group: us-sc/form/individual_income_tax_forms
    source_family: individual_income_tax_forms
    source_status: primary_official
    source_discovery_input_count: 1
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://dor.sc.gov/sites/dor/files/forms/SC1040_2025.pdf
    discovered_via: source-discovery:all_url
