documents:
- source_id: sites-default-files-vatax-pdf-2024-760-instructions-cc308fd8c5
  jurisdiction: us-va
  document_class: form
  citation_path: us-va/form/tax_forms/tax.virginia.gov/sites/default/files/vatax-pdf/2024-760-instructions
  title: 2024-760-instructions
  source_url: https://tax.virginia.gov/sites/default/files/vatax-pdf/2024-760-instructions.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: tax.virginia.gov
    source_discovery_group: us-va/form/tax_forms
    source_family: tax_forms
    source_status: primary_official
    source_discovery_input_count: 14
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://www.tax.virginia.gov/sites/default/files/vatax-pdf/2024-760-instructions.pdf#page=15
    discovered_via: source-discovery:all_url
- source_id: sites-default-files-vatax-pdf-2022-760-instructions-8467cdee98
  jurisdiction: us-va
  document_class: form
  citation_path: us-va/form/tax_forms/tax.virginia.gov/sites/default/files/vatax-pdf/2022-760-instructions
  title: 2022-760-instructions
  source_url: https://tax.virginia.gov/sites/default/files/vatax-pdf/2022-760-instructions.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: tax.virginia.gov
    source_discovery_group: us-va/form/tax_forms
    source_family: tax_forms
    source_status: primary_official
    source_discovery_input_count: 12
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://www.tax.virginia.gov/sites/default/files/vatax-pdf/2022-760-instructions.pdf
    discovered_via: source-discovery:all_url
- source_id: sites-default-files-vatax-pdf-2023-760-instructions-09da79ceb6
  jurisdiction: us-va
  document_class: form
  citation_path: us-va/form/tax_forms/tax.virginia.gov/sites/default/files/vatax-pdf/2023-760-instructions
  title: 2023-760-instructions
  source_url: https://tax.virginia.gov/sites/default/files/vatax-pdf/2023-760-instructions.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: tax.virginia.gov
    source_discovery_group: us-va/form/tax_forms
    source_family: tax_forms
    source_status: primary_official
    source_discovery_input_count: 11
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://www.tax.virginia.gov/sites/default/files/vatax-pdf/2023-760-instructions.pdf
    discovered_via: source-discovery:all_url
- source_id: sites-default-files-vatax-pdf-2021-760-instructions-c401d40925
  jurisdiction: us-va
  document_class: form
  citation_path: us-va/form/tax_forms/tax.virginia.gov/sites/default/files/vatax-pdf/2021-760-instructions
  title: 2021-760-instructions
  source_url: https://tax.virginia.gov/sites/default/files/vatax-pdf/2021-760-instructions.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: tax.virginia.gov
    source_discovery_group: us-va/form/tax_forms
    source_family: tax_forms
    source_status: primary_official
    source_discovery_input_count: 10
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://www.tax.virginia.gov/sites/default/files/vatax-pdf/2021-760-instructions.pdf#page=11
    discovered_via: source-discovery:all_url
- source_id: sites-default-files-vatax-pdf-2025-760-instructions-e5cbf6bf94
  jurisdiction: us-va
  document_class: form
  citation_path: us-va/form/tax_forms/tax.virginia.gov/sites/default/files/vatax-pdf/2025-760-instructions
  title: 2025-760-instructions
  source_url: https://tax.virginia.gov/sites/default/files/vatax-pdf/2025-760-instructions.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: tax.virginia.gov
    source_discovery_group: us-va/form/tax_forms
    source_family: tax_forms
    source_status: primary_official
    source_discovery_input_count: 10
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://www.tax.virginia.gov/sites/default/files/vatax-pdf/2025-760-instructions.pdf#page=15
    discovered_via: source-discovery:all_url
- source_id: sites-default-files-vatax-pdf-2019-schedule-a-instructions-6100463c89
  jurisdiction: us-va
  document_class: form
  citation_path: us-va/form/tax_forms/tax.virginia.gov/sites/default/files/vatax-pdf/2019-schedule-a-instructions
  title: 2019-schedule-a-instructions
  source_url: https://tax.virginia.gov/sites/default/files/vatax-pdf/2019-schedule-a-instructions.pdf
  source_format: pdf
  source_as_of: '2026-05-23'
  metadata:
    primary_source: true
    source_authority: tax.virginia.gov
    source_discovery_group: us-va/form/tax_forms
    source_family: tax_forms
    source_status: primary_official
    source_discovery_input_count: 1
    source_discovery_source_list: all_url
    source_discovery_raw_url: https://www.tax.virginia.gov/sites/default/files/vatax-pdf/2019-schedule-a-instructions.pdf#page=2
    discovered_via: source-discovery:all_url
