#!/usr/bin/env python3
"""Fold an ingestion wave's decisions into the program bundles' joins file.

Each wave agent writes `docs/ingest-runs/<date>-<wave>-<group>-decisions.csv`,
one row per document of its work order (`docs/coverage/<gaps>/<wave>/<group>.csv`):
the new status, and the scope and citation path that hold the document. The
bundles name many documents by the address PolicyEngine cites; this script
records, for each such address:

- `document_paths`: the corpus path that holds it (PRESENT, ALREADY-HELD), so
  the bundle counts the served document even when no manifest names the
  address (a section of a whole code taken from its legislature, or an
  official copy of a law PolicyEngine cites from a mirror);
- `not_sources`: why it is no source of rules (OUT-OF-SCOPE), so the bundle
  excludes it with that reason.

OUTREACH, ABSENT and SKIPPED documents stay in the bundles as not in the corpus.

    python scripts/apply_wave_decisions.py \\
      --work-orders docs/coverage/program-bundle-gaps-2026-10-06/wave6 \\
      --decisions <decisions.csv> [<decisions.csv> ...] \\
      --out manifests/program-bundles/joins.yaml
"""

from __future__ import annotations

import argparse
import csv
from collections import Counter
from pathlib import Path

import yaml

HELD = {"PRESENT", "ALREADY-HELD"}


def read_work_orders(folder: Path) -> dict[str, dict]:
    """Every work-order row, by its document identity."""
    rows = {}
    for path in sorted(folder.glob("*.csv")):
        with path.open(newline="") as f:
            for row in csv.DictReader(f):
                rows[row["id"]] = row
    return rows


def joins(
    work_orders: dict[str, dict], decisions: list[dict], existing: dict
) -> tuple[dict, Counter]:
    """The joins file with the decisions folded in, and the decisions by status."""
    paths = dict(existing.get("document_paths") or {})
    not_sources = dict(existing.get("not_sources") or {})
    statuses: Counter = Counter()
    for row in decisions:
        status = (row.get("new_status") or "").strip()
        statuses[status] += 1
        order = work_orders.get(row["id"])
        if order is None:
            raise SystemExit(f"decision for {row['id']!r} matches no work-order row")
        url = order["bundle_url"]
        if not url:
            # A document the bundle already names by its corpus path joins by that path.
            continue
        if status in HELD:
            path = (row.get("citation_path") or "").strip()
            if not path:
                raise SystemExit(f"{status} decision for {url} names no citation path")
            paths[url] = path
        elif status == "OUT-OF-SCOPE":
            note = (row.get("note") or "").strip()
            not_sources[url] = f"Not a source of rules: {note}" if note else "Not a source of rules"
    out = {
        "same_document": existing.get("same_document") or {},
        "document_paths": dict(sorted(paths.items())),
        "not_sources": dict(sorted(not_sources.items())),
    }
    return out, statuses


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--work-orders", type=Path, required=True)
    ap.add_argument("--decisions", type=Path, nargs="+", required=True)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()
    work_orders = read_work_orders(args.work_orders)
    decisions = []
    for path in args.decisions:
        with path.open(newline="") as f:
            decisions.extend(csv.DictReader(f))
    existing = yaml.safe_load(args.out.read_text()) if args.out.exists() else {}
    out, statuses = joins(work_orders, decisions, existing or {})
    header = (
        "# Generated by scripts/apply_wave_decisions.py from the ingestion waves' decisions files;\n"
        "# edit the decisions, not this file.\n"
    )
    args.out.write_text(
        header + yaml.safe_dump(out, sort_keys=False, allow_unicode=True, width=1000)
    )
    print(
        f"{len(decisions)} decisions ({', '.join(f'{k} {v}' for k, v in statuses.most_common())}); "
        f"{len(out['document_paths'])} addresses joined to a path, {len(out['not_sources'])} not sources"
    )


if __name__ == "__main__":
    main()
